import RootLayout from "@/components/Layouts/RootLayouts";
import Banner from "@/components/UI/Banner";
import Card from "@/components/UI/Card";
import Features from "@/components/UI/Features";
import Head from "next/head";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="home" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner></Banner>
        <Features></Features>
        <>
          <div className="grid gap-3 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            {data?.data?.map((product) => (
              <Card product={product} key={product._id}></Card>
            ))}
          </div>
        </>
      </div>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};

export const getStaticProps = async () => {
  const res = await fetch(
    "https://pc-builder-tawny.vercel.app/api/randomitems"
  );
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};
