import RootLayout from "@/components/Layouts/RootLayouts";
import Banner from "@/components/UI/Banner";
import Features from "@/components/UI/Features";
import Head from "next/head";

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="home" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner></Banner>
        <Features></Features>
      </div>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};

export const getStaticProps = async () => {
  if (typeof window === "undefined") {
    const res = await fetch(
      "https://pc-builder-tawny.vercel.app/api/randomitems"
    );
    const data = await res.json();
    return {
      props: {
        data,
      },
    };
  } else {
    const res = await fetch("https://pc-builder-tawny.vercel.app/api/items");
    const data = await res.json();
    return {
      props: {
        data,
      },
    };
  }
};
